spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names:
        master,slave,slave2
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/python?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/python?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/python?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
    masterslave:
      # 读写分离配置  可选值：ROUND_ROBIN(轮询)，RANDOM（随机）
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave,slave2
    props:
      # 开启SQL显示，默认false
      sql:
        show: true
