server:
  port: 8881


#异步线程配置
async:
  executor:
    thread:
    #配置核心线程数
      core_pool_size: 10
    #配置最大线程数
      max_pool_size: 20
    #配置队列大小
      queue_capacity: 9999
    #配置线程池中的线程的名称前缀
      name_prefix: = async-service-